stages:
  - build
  - deploy

build test-backend:
  stage: build

  script:
    - ./gradlew build
    - docker build -t test-backend .
deploy test-backend:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d