version: "3.9" # optional since v1.27.0
services:
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=${username}
      - POSTGRES_PASSWORD=${password}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
